### ISSUE TITLE
You CoC config setup

### ISSUE THREAD

**Issue by rcidaleassumpo** [jamesonweber/nvim#1]
Hi James, 
Not really an issue, but that was the best way to try and get a hold of you! 

I'm trying to get CoC to work for auto import together with aliases. The normal autoimport works, where I get the '../../whatevermodule', but it doesn't add an option of aliases to it, so instead would be like '@/whatevermodule'
Do you have any idea on how I would be able to solve that? I have being trying to communicate and ask in the tsserver issue, but is being very dry :(..

Thanks anyway !

**Comment by jamesonweber** [comment]
Hi @rcidaleassumpo!

Sorry I didn't reply earlier. It seems I wasn't watching my own repo, so I didn't get a notification about this. I hope you have resolved the issue, since the time this was posted.

For my set up, I have this line added to my coc-settings: https://github.com/jamesonweber/nvim/blob/master/coc-settings.json#L6

It forces a relative import for everything (which is the only method of importing I use). I think you can force other options as well (by default I think it is "auto"). So I think if you use "non-relative" as the option, it might force imports to do what you are looking for.

Other than that, I am not sure. I am fairly new to this platform, and I just picked up vim a few months ago. But I hope this helps!
